num = int(input('в ведите число:'))

result = pow(num, 0)
print(result)
result = pow(num, 1)
print(result)
result = pow(num, 2)
print(result)
result = pow(num, 3)
print(result)
result = pow(num, 5)
print(result)
result = pow(num, 6)
print(result)
result = pow(num, 7)
print(result)

